# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94faca076027b5bb5de7c689066f40b3544c710420259ec35f3ada9e24b84cc63918a609511a0478eac2dd197dd2f8a5b35c557c05204de754a1ecf215585035

test:
  secret_key_base: 6fd8a98446f74e1e204a4307dc6998e4bc04a393d8c6e230ca514fc3a8a60e6441dd190437e601822593284b576a1c39798a00bf3871ee368d1af57171836d33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
